pub mod eof_before_tag_name_parse_error;
pub mod invalid_first_character_of_tag_name_parse_error;
pub mod missing_end_tag_name_parse_error;
pub mod unexpected_null_character_parse_error;
pub mod unexpected_question_mark_instead_of_tag_name_parse_error;
