use std::fmt::{
  Display,
  Formatter,
  Result
};

#[derive(Debug, PartialEq)]
pub enum DataState {
  AfterAttributeNameState,
  AfterAttributeQuotedState,
  AfterDOCTYPENameState,
  AfterDOCTYPEPublicIdentifierState,
  AfterDOCTYPEPublicKeywordState,
  AfterDOCTYPESystemIdentifierState,
  AfterDOCTYPESystemKeywordState,
  AmbiguousAmpersandState,
  AttributeNameState,
  AttributeValueDoubleQuotedState,
  AttributeValueSingleQuotedState,
  AttributeValueUnquotedState,
  BeforeAttributeNameState,
  BeforeAttributeValueState,
  BeforeDOCTYPENameState,
  BeforeDOCTYPEPublicIdentifierState,
  BeforeDOCTYPESystemIdentifierState,
  BetweenDOCTYPEPublicAndSystemIdentifiersState,
  BogusCommentState,
  BogusDOCTYPEState,
  CDATASectionBracketState,
  CDATASectionEndState,
  CDATASectionState,
  CharacterReferenceState,
  CommentEndBangState,
  CommentEndDashState,
  CommentEndState,
  CommentLessThanSignBangDashDashState,
  CommentLessThanSignBangDashState,
  CommentLessThanSignBangState,
  CommentLessThanSignState,
  CommentStartDashState,
  CommentStartState,
  CommentState,
  DataState,
  DecimalCharacterReferenceStartState,
  DecimalCharacterReferenceState,
  DOCTYPENameState,
  DOCTYPEPublicIdentifierDoubleQuotedState,
  DOCTYPEPublicIdentifierSingleQuotedState,
  DOCTYPEState,
  DOCTYPESystemIdentifierDoubleQuotedState,
  DOCTYPESystemIdentifierSingleQuotedState,
  EndTagOpenState,
  HexadecimalCharacterReferenceStartState,
  HexidecimalCharacterReferenceState,
  MarkupDeclarationOpenState,
  NamedCharacterReferenceState,
  NumericCharacterReferenceEndState,
  NumericCharacterReferenceState,
  PLAINTEXTState,
  RAWTEXTEndTagNameState,
  RAWTEXTEndTagOpenState,
  RAWTEXTLessThanSignState,
  RAWTEXTState,
  RCDATAEndTagNameState,
  RCDATAEndTagOpenState,
  RCDATALessThanSignState,
  RCDataState,
  ScriptDataDDoubleEscapedDashState,
  ScriptDataDoubleEscapedDashState,
  ScriptDataDoubleEscapedLessThanSignState,
  ScriptDataDoubleEscapedState,
  ScriptDataDoubleEscapeEndState,
  ScriptDataDoubleEscapeStartState,
  ScriptDataEndTagNameState,
  ScriptDataEndTagOpenState,
  ScriptDataEscapedDashDashState,
  ScriptDataEscapedDashState,
  ScriptDataEscapedEndTagNameState,
  ScriptDataEscapedEndTagOpenState,
  ScriptDataEscapedLessThanSignState,
  ScriptDataEscapedState,
  ScriptDataEscapeStartDashState,
  ScriptDataEscapeStartDate,
  ScriptDataLessThanSignState,
  ScriptDataState,
  SelfClosingStartTagState,
  TagNameState,
  TagOpenState,
}

impl Default for DataState {
  fn default() -> Self {
    return DataState::DataState;
  }
}

impl Display for DataState {
  fn fmt(&self, f: &mut Formatter) -> Result {
    write!(f, "{:?}", self)
  }
}
